### ISSUE TITLE
Logging and error handling

### ISSUE THREAD

**Issue by omron93** [napalm-automation-community/napalm-srlinux#24]
Current behaviour of the driver is that it catches the exceptions and uses "stdout" print for saying what went wrong, but it's not re-raising the exceptions.
One example of how this handling provides "weird" output is when doing following operations with incorrect credentials
```
with driver(<args>) as device:
  result = device.get_config(retrieve='running')
  config = result['running']
```
This code doesn't fail on the open() nor the get_config() calls.
```
>>> result['running']
...
TypeError: 'NoneType' object is not subscriptable
```
So this makes the debugging harder also I would say it's quite non-standard.

The other thing is the logging. The prints statements are hard to integrate into other applications, and the driver can also be used with other than CLI programs. So it's not possible to make the prints integrated with logging files for long-running processes/service or with centralised logging systems.

My suggestion is to replace the prints statements with logging module and to reraise the exceptions (either the same or based on napalm library exceptions). Happy to hear other opinions on the logging and exceptions handling problem described above.

**Comment by jbemmel** [comment]
Hi @omron93, thank you for raising the issue. Yes, we are aware that logging and exception handling logic leaves some things to be desired - in part also because error handling isn't always clearly defined by NAPALM

In the example that you describe, the username+password aren't checked until the get_config call is made - and while open() could validate them by making some dummy request, none of the other drivers do that - so we left it like that.

That being said, see https://github.com/napalm-automation-community/napalm-srlinux/pull/34 for slightly improved error handling/logging for some of the more common methods ( open(), close() and get_config() to start ), replacing all print() calls with logging.error().

Let us know if that helps

**Comment by jbemmel** [comment]
Implemented enhancements in https://github.com/napalm-automation-community/napalm-srlinux/pull/34
